name: wsi-pre2
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.9.*
  - openslide=3.4.1 # C-Library, latest release from 2015
  - openslide-python=1.2.0 # Python binding, release from 2022
  - pre-commit=3.*
  - pip:
      - opencv-python==4.5.5.62
      - Pillow==9.5.0
      - pandas==1.5.2 # Before switching from Numpy to Apache Arrow backend
      - numpy==1.24.4
      - matplotlib==3.7.*
      - tqdm==4.66.1
