# Helpful resources:
# 1.) https://autobencoder.com/2020-08-24-conda-actions/
# 2.) https://github.com/conda-incubator/setup-miniconda

name: Test Env

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_env_tests:
    name: Test Env (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]  # Openslide not available via conda on Windows
        os: ["ubuntu-latest"]
    defaults:
      run:
        shell: bash -el {0} # Need to adjust shell to remember profile
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yaml
          auto-activate-base: false
      - run: |
          conda info
          conda list
